2021-04-04 21:23:38 [twisted] CRITICAL: Unhandled error in Deferred:
2021-04-04 21:23:38 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "g:\sourcecode\python\stock-tracker\env\lib\site-packages\twisted\internet\defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File "g:\sourcecode\python\stock-tracker\env\lib\site-packages\scrapy\crawler.py", line 88, in crawl
    start_requests = iter(self.spider.start_requests())
TypeError: 'Request' object is not iterable
2021-04-04 21:25:15 [scrapy.core.engine] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "g:\sourcecode\python\stock-tracker\env\lib\site-packages\scrapy\core\engine.py", line 129, in _next_request
    request = next(slot.start_requests)
  File "G:\SourceCode\python\stock-tracker\stock\stock\spiders\stock_dividend.py", line 29, in start_requests
    yield scrapy.Request(url=url, callback=self.parse, cb_kwargs={'stockCode': 2330})
  File "g:\sourcecode\python\stock-tracker\env\lib\site-packages\scrapy\http\request\__init__.py", line 25, in __init__
    self._set_url(url)
  File "g:\sourcecode\python\stock-tracker\env\lib\site-packages\scrapy\http\request\__init__.py", line 63, in _set_url
    raise TypeError(f'Request url must be str or unicode, got {type(url).__name__}')
TypeError: Request url must be str or unicode, got tuple
2021-04-04 21:26:06 [scrapy.core.engine] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "g:\sourcecode\python\stock-tracker\env\lib\site-packages\scrapy\core\engine.py", line 129, in _next_request
    request = next(slot.start_requests)
  File "G:\SourceCode\python\stock-tracker\stock\stock\spiders\stock_dividend.py", line 29, in start_requests
    yield scrapy.Request(url=url, callback=self.parse, cb_kwargs={'stockCode': 2330})
  File "g:\sourcecode\python\stock-tracker\env\lib\site-packages\scrapy\http\request\__init__.py", line 25, in __init__
    self._set_url(url)
  File "g:\sourcecode\python\stock-tracker\env\lib\site-packages\scrapy\http\request\__init__.py", line 63, in _set_url
    raise TypeError(f'Request url must be str or unicode, got {type(url).__name__}')
TypeError: Request url must be str or unicode, got tuple
